services:
  shopApp:
    build:
      context: .
      dockerfile: YandexPracticumShopApp/Dockerfile
    image: yandex-shop-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - C:/yandexShopApp/images:/yandexShopApp/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://yandex_shop_db:5432/yandex_shop
      SPRING_R2DBC_URL: r2dbc:postgresql://yandex_shop_db/yandex_shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: yandex_shop_redis
      PAYMENT_SERVICE_URL: paymentApp
      HOST_IMAGES_PATH: ./yandexShopApp/images
    depends_on:
      - db
      - redis
  paymentApp:
    build:
      context: .
      dockerfile: YandexPracticumPaymentsApp/Dockerfile
    image: yandex-payment-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      PAYMENT_SERVICE_URL: paymentApp
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    container_name: yandex_shop_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yandex_shop
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6380:6379"
    container_name: yandex_shop_redis